### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by minimon10x** [motivational-dragon/Potion-Blender#15]
When I throw the nether wart in, it just sits in the cauldron. Nothing happens, and when I right click it just  takes the ingrediants out. Shift-right clicking doesn't help either, and left clicking doesn't. The dragon's breath and gunpowder just disappear when I put them in, but they still raise the water level. This is 1.20.1 forge 47.3.10

**Comment by motivational-dragon** [comment]
Hello,

First, could you please send the step you did in order for me to reproduce the issue? If you did not put any potion to merge then it is normal that nothing happen as there is no recipe to trigger.

Typically you would do:

1. Throw the potions in the cauldron: for instance a potion of healing and a potion of poison
2. Throw a nether wart, a fire effect sound play
3. Wait a few seconds for the recipe to complete
4. The resulting item is ejected from the cauldron

Secondly Items disappearing in the cauldron is probably because you need to set your graphic setting to "Fabulous" for them to display due to the way minecraft rendering work.

Finally, please send your minecraft log.txt, otherwise it is impossible to know if there is an error.

**Comment by minimon10x** [comment]
Sorry for replying so late!

I threw in (with Q) a strength 8 min, fire res 8 min, and a regen 1.5 min,
then threw in the nether wart. No sound effect played, and the items just
sat there. I do not know what log.txt is.

**Comment by motivational-dragon** [comment]
No problems. I published a new version (3.1.1.1) for MC 1.20.1 since the old version had a recipe bug. Also i just realized that in the version you used the cauldron was off by default  when place in creative (you can lit it using a flint and steel like a campfire). I updated that in the latest version. Can you try the updated version?

**Comment by minimon10x** [comment]
Yes it worked, thank you. I'm impressed by how quickly this was responded.
Sorry for my own delay.
